name:                nlu-parsers
version:             0.1.0.0
github:              "hgoldstein95/nlu-parsers"
license:             BSD3
author:              "Harrison Goldstein"
maintainer:          "hgoldstein95@gmail.com"
copyright:           "2018 Harrison Goldstein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/hgoldstein95/nlu-parsers#readme>

dependencies:
- base >= 4.7 && < 5
- hext
- mtl
- text
- containers

library:
  source-dirs: src

executables:
  nlu-parsers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nlu-parsers

tests:
  nlu-parsers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nlu-parsers
